CREATE TABLE `mahasiswa` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id_mahasiswa` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nim` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama_mahasiswa` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tempat_lahir` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_agama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_agama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_lahir` date DEFAULT NULL,
  `jenis_kelamin` enum('L','P') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alamat` text COLLATE utf8mb4_unicode_ci,
  `jalan` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rt` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rw` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `kelurahan` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `kecamatan` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `kota_kabupaten` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provinsi` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `kode_pos` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_wilayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_wilayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_jenis_tinggal` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_jenis_tinggal` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_alat_transportasi` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_alat_transportasi` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `no_hp` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alamat_ortu` text COLLATE utf8mb4_unicode_ci,
  `rt_ortu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rw_ortu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kelurahan_ortu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kecamatan_ortu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kota_kabupaten_ortu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provinsi_ortu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_ayah` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nik_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_lahir_ayah` date DEFAULT NULL,
  `id_pendidikan_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_pendidikan_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_pekerjaan_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_pekerjaan_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_penghasilan_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_penghasilan_ayah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pekerjaan_ayah` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama_ibu` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_lahir_wali` date DEFAULT NULL,
  `id_pendidikan_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_pendidikan_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_pekerjaan_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_pekerjaan_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_penghasilan_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_penghasilan_wali` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nik_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_lahir_ibu` date DEFAULT NULL,
  `id_pendidikan_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_pendidikan_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_pekerjaan_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_pekerjaan_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_penghasilan_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_penghasilan_ibu` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pekerjaan_ibu` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `program_studi_id` bigint unsigned DEFAULT NULL,
  `id_prodi` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `angkatan` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_periode` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_mahasiswa` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_status_mahasiswa` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_status_mahasiswa` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_registrasi_mahasiswa` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ID Registrasi dari Neo Feeder',
  `ipk` decimal(4,2) DEFAULT NULL,
  `sks_tempuh` int DEFAULT NULL,
  `dusun` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nik` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nisn` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `npwp` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `kewarganegaraan` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telepon` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `handphone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dosen_wali_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `id_kebutuhan_khusus_mahasiswa` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_kebutuhan_khusus_mahasiswa` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_kebutuhan_khusus_ayah` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_kebutuhan_khusus_ayah` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_kebutuhan_khusus_ibu` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_kebutuhan_khusus_ibu` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keterangan_keluar` text COLLATE utf8mb4_unicode_ci,
  `tanggal_keluar` date DEFAULT NULL,
  `id_periode_keluar` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_sk_yudisium` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sk_yudisium` date DEFAULT NULL,
  `nomor_ijazah` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mahasiswa_id_mahasiswa_unique` (`id_mahasiswa`),
  UNIQUE KEY `mahasiswa_nim_unique` (`nim`),
  KEY `mahasiswa_dosen_wali_id_foreign` (`dosen_wali_id`),
  KEY `mahasiswa_nim_index` (`nim`),
  KEY `mahasiswa_nama_index` (`nama`),
  KEY `mahasiswa_program_studi_id_index` (`program_studi_id`),
  CONSTRAINT `mahasiswa_dosen_wali_id_foreign` FOREIGN KEY (`dosen_wali_id`) REFERENCES `dosen` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mahasiswa_program_studi_id_foreign` FOREIGN KEY (`program_studi_id`) REFERENCES `program_studi` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci